export const COVERAGE = {
  HAS_RECORD: 'HAS_RECORD',
  NO_RECORD: 'NO_REPORTING_RECORD'
}

export const RISK_TAG_CODES = [
  'PLAN_DATE_PASSED',
  'NEAR_PLAN_DATE',
  'LOW_STORED_COMPLETION',
  'REPORTING_SILENCE',
  'NO_REPORTING_RECORD',
  'HAS_DEFECTIVE_RECORD'
]

export const RISK_TAG_STYLE = {
  PLAN_DATE_PASSED: 'danger',
  NEAR_PLAN_DATE: 'warning',
  LOW_STORED_COMPLETION: 'warning',
  REPORTING_SILENCE: 'warning',
  NO_REPORTING_RECORD: 'info',
  HAS_DEFECTIVE_RECORD: 'danger'
}
