import { request } from './request'
import type { CrudApi, Row, Field } from './crud'
export function platformApi(resource:string):CrudApi { const path = '/api/platform/' + resource; return { list: q => request(path, { query: q, scope: 'platform' }), create: body => request(path, { method: 'POST', body, scope: 'platform' }), update: (id, body) => request(path + '/' + encodeURIComponent(id), { method: 'PUT', body, scope: 'platform' }), remove: id => request(path + '/' + encodeURIComponent(id), { method: 'DELETE', scope: 'platform' }) } }
const status:Field = { key: 'status', label: '状态', kind: 'select', required: true, options: [{ label: '启用', value: 'ENABLED' }, { label: '停用', value: 'DISABLED' }] }
const id:Field = { key: 'id', label: '标识', kind: 'text', readonly: true, hidden: true }
const text = (key:string, label:string, required = true):Field => ({ key, label, kind: 'text', required, maxLength: 100 })
export interface PlatformPage { title: string;resource: string;permission: string;fields: Field[];readonly?: boolean }
export const pages:Record<string, PlatformPage> = {
  users: { title: '用户管理', resource: 'users', permission: 'platform:users', fields: [id, text('username', '登录账号'), text('displayName', '显示名称'), status, { key: 'password', label: '初始密码（至少12位）', kind: 'password', required: true, maxLength: 128 }, { key: 'createdAt', label: '创建时间', kind: 'datetime', readonly: true }] },
  roles: { title: '角色与范围', resource: 'roles', permission: 'platform:roles', fields: [id, text('name', '角色名称'), { key: 'kind', label: '角色范围', kind: 'select', required: true, options: [{ label: '平台管理', value: 'PLATFORM' }, { label: '工厂业务', value: 'FACTORY' }] }, { ...text('factoryId', '工厂标识'), showWhen: { key: 'kind', value: 'FACTORY' }}, status] },
  menus: { title: '菜单与权限', resource: 'menus', permission: 'platform:menus', fields: [id, text('parentId', '上级菜单标识', false), text('name', '菜单名称'), text('path', '页面路径'), text('permission', '权限编码'), { key: 'sortOrder', label: '排序', kind: 'number', required: true }, { key: 'kind', label: '节点类型', kind: 'select', required: true, options: [{ label: '菜单', value: 'MENU' }, { label: '按钮', value: 'BUTTON' }] }] },
  'dict-types': { title: '字典类型', resource: 'dict-types', permission: 'platform:dict-types', fields: [id, text('code', '类型编码'), text('name', '类型名称')] },
  'dict-data': { title: '字典内容', resource: 'dict-data', permission: 'platform:dict-data', fields: [id, text('typeId', '字典类型标识'), text('value', '值'), text('label', '显示文本'), { key: 'sortOrder', label: '排序', kind: 'number', required: true }] },
  configs: { title: '参数配置', resource: 'configs', permission: 'platform:configs', fields: [id, text('configKey', '配置键'), text('configValue', '配置值'), { key: 'kind', label: '配置范围', kind: 'select', required: true, options: [{ label: '平台全局', value: 'GLOBAL' }, { label: '工厂独立', value: 'FACTORY' }] }, { ...text('factoryId', '工厂标识'), showWhen: { key: 'kind', value: 'FACTORY' }}] },
  jobs: { title: '任务调度', resource: 'jobs', permission: 'platform:jobs', fields: [id, text('name', '任务名称'), { key: 'handler', label: '已登记任务', kind: 'select', required: true, options: [{ label: '平台心跳', value: 'platform-heartbeat' }, { label: '工厂心跳', value: 'factory-heartbeat' }] }, { key: 'executionScope', label: '执行范围', kind: 'select', required: true, options: [{ label: '平台', value: 'PLATFORM' }, { label: '工厂', value: 'FACTORY' }] }, { ...text('factoryId', '工厂标识'), showWhen: { key: 'executionScope', value: 'FACTORY' }}, text('cron', 'Cron（UTC）'), status] },
  audit: { title: '操作审计', resource: 'audit', permission: 'platform:logs', readonly: true, fields: [id, text('requestId', '请求标识'), text('actorId', '操作人'), text('factoryId', '工厂', false), text('executionScope', '执行范围'), text('action', '操作'), text('outcome', '结果'), { key: 'createdAt', label: '时间（UTC）', kind: 'datetime' }] },
  'login-logs': { title: '登录日志', resource: 'login-logs', permission: 'platform:logs', readonly: true, fields: [id, text('requestId', '请求标识'), text('actorId', '账号'), text('outcome', '结果'), { key: 'createdAt', label: '时间（UTC）', kind: 'datetime' }] },
  'job-logs': { title: '执行日志', resource: 'job-logs', permission: 'platform:logs', readonly: true, fields: [id, text('jobId', '任务标识'), text('requestId', '请求标识'), text('actorId', '执行人'), text('factoryId', '工厂', false), text('executionScope', '执行范围'), text('outcome', '结果'), { key: 'createdAt', label: '时间（UTC）', kind: 'datetime' }] }
}
export function pageApi(page:PlatformPage):CrudApi { const api = platformApi(page.resource);if (page.resource === 'users') { const build = (raw:unknown) => { const d = raw as Row;return { username: d.username, displayName: d.displayName, status: d.status } };return { ...api, create: raw => api.create({ user: build(raw), credential: { password: (raw as Row).password }}), update: (id, raw) => api.update(id, build(raw)) } } return api }
