<script setup lang="ts">
// SOURCE_PRODUCT_PORT: original Quill toolbar/events; Vue3 + private file transport.
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';import Quill from 'quill';import DOMPurify from 'dompurify';import { ElMessage } from 'element-plus';import { request, requestBlob } from '@/lib/request';import 'quill/dist/quill.snow.css'
const props = withDefaults(defineProps<{ modelValue?: string;height?: number;minHeight?: number;readOnly?: boolean;fileSize?: number;type?: string }>(), { modelValue: '', height: undefined, minHeight: 192, readOnly: false, fileSize: 5, type: 'url' });const emit = defineEmits(['update:modelValue', 'on-change', 'on-text-change', 'on-selection-change', 'on-editor-change']);const editor = ref<HTMLElement>(), upload = ref<HTMLInputElement>();let quill:Quill | undefined;let mediaType = 'image';const blobs = new Set<string>()
const mediaPattern = /^\/api\/platform\/files\/([a-f0-9-]{36})\/content\?resource=notice-media$/
function safeHtml(value:string) { const html = DOMPurify.sanitize(value, { ADD_TAGS: ['video'], ADD_ATTR: ['data-file-id', 'data-resource', 'controls'] });const doc = new DOMParser().parseFromString(html, 'text/html');for (const node of doc.querySelectorAll('img,video')) if (!mediaPattern.test(node.getAttribute('src') ?? ''))node.remove();return doc.body.innerHTML }
function serialize() { if (!quill) return '';const clone = quill.root.cloneNode(true) as HTMLElement;for (const node of clone.querySelectorAll('img[data-file-id],video[data-file-id]'))node.setAttribute('src', '/api/platform/files/' + node.getAttribute('data-file-id') + '/content?resource=notice-media');return safeHtml(clone.innerHTML) }
async function hydrate(node:HTMLElement, source:string) { const match = source.match(mediaPattern);if (!match) return;node.dataset.fileId = match[1];node.dataset.resource = 'notice-media';try { const blob = await requestBlob(source, { scope: 'platform' });const url = URL.createObjectURL(blob);blobs.add(url);if (editor.value?.contains(node))node.setAttribute('src', url);else { URL.revokeObjectURL(url);blobs.delete(url) } } catch { node.setAttribute('aria-label', '附件无权限或已删除');node.removeAttribute('src') } }
onMounted(() => {
  const Image = Quill.import('formats/image') as any;const BlockEmbed = Quill.import('blots/block/embed') as any
  class PrivateImage extends Image {static sanitize(value:string) { return mediaPattern.test(value) ? value : 'about:blank' } static create(value:string) { const node = super.create(value) as HTMLElement;void hydrate(node, value);return node } static value(node:HTMLElement) { return '/api/platform/files/' + node.dataset.fileId + '/content?resource=notice-media' }}
  class PrivateVideo extends BlockEmbed {static blotName = 'video';static tagName = 'VIDEO';static create(value:string) { const node = super.create() as HTMLElement;node.setAttribute('controls', '');node.setAttribute('preload', 'metadata');void hydrate(node, value);return node } static value(node:HTMLElement) { return '/api/platform/files/' + node.dataset.fileId + '/content?resource=notice-media' }}
  Quill.register(PrivateImage, true);Quill.register(PrivateVideo, true)
  quill = new Quill(editor.value!, { theme: 'snow', placeholder: '请输入内容', readOnly: props.readOnly, modules: { toolbar: [['bold', 'italic', 'underline', 'strike'], ['blockquote', 'code-block'], [{ list: 'ordered' }, { list: 'bullet' }], [{ indent: '-1' }, { indent: '+1' }], [{ size: ['small', false, 'large', 'huge'] }], [{ header: [1, 2, 3, 4, 5, 6, false] }], [{ color: [] }, { background: [] }], [{ align: [] }], ['clean'], ['link', 'image', 'video']] }})
  const toolbar = quill.getModule('toolbar') as { addHandler: (type:string, handler:() => void) => void };for (const kind of ['image', 'video'])toolbar.addHandler(kind, () => { mediaType = kind;if (upload.value) { upload.value.accept = kind === 'image' ? 'image/png,image/jpeg,image/gif,image/webp' : 'video/mp4';upload.value.click() } })
  quill.clipboard.dangerouslyPasteHTML(safeHtml(props.modelValue), 'silent');quill.on('text-change', (delta, old, source) => { const html = serialize();emit('update:modelValue', html);emit('on-change', { html, text: quill?.getText(), quill });emit('on-text-change', delta, old, source) });quill.on('selection-change', (...args) => emit('on-selection-change', ...args));quill.on('editor-change', (...args) => emit('on-editor-change', ...args))
})
watch(() => props.modelValue, value => { if (quill && serialize() !== safeHtml(value))quill.clipboard.dangerouslyPasteHTML(safeHtml(value), 'silent') });watch(() => props.readOnly, value => quill?.enable(!value));onBeforeUnmount(() => { for (const url of blobs)URL.revokeObjectURL(url);blobs.clear();quill = undefined })
async function uploadMedia(event:Event) { const input = event.target as HTMLInputElement;const file = input.files?.[0];if (!file) return;try { if (file.size > props.fileSize * 1024 * 1024) throw new Error(`文件不能超过 ${props.fileSize} MB`);const data = new FormData();data.set('file', file);const saved = await request<{ fileId: string }>('/api/platform/files', { method: 'POST', body: data, query: { resource: 'notice-media' }, scope: 'platform' });const at = quill?.getSelection()?.index ?? quill?.getLength() ?? 0;quill?.insertEmbed(at, mediaType, '/api/platform/files/' + saved.fileId + '/content?resource=notice-media', 'user');quill?.setSelection(at + 1, 0, 'silent') } catch(error) { ElMessage.error(error instanceof Error ? error.message : '附件插入失败') } finally { input.value = '' } }
</script><template><div class="source-editor"><input ref="upload" type="file" hidden @change="uploadMedia"><div ref="editor" :style="{minHeight:minHeight+'px',height:height?height+'px':undefined}" /></div></template>
<style>.source-editor .ql-editor{min-height:192px;line-height:1.6}.source-editor video,.source-editor img{max-width:100%}.ql-snow .ql-tooltip[data-mode="link"]::before{content:'请输入链接地址：'}.ql-snow .ql-picker.ql-header .ql-picker-label::before{content:'正文'}.ql-snow .ql-tooltip.ql-editing a.ql-action::after{content:'保存'}</style>
