import { describe, it, expect, vi, beforeEach } from 'vitest'
import { request, configureRequests, ApiError } from '../src/lib/request'
let revision = 0;const unauthorized = vi.fn()
beforeEach(() => { revision = 0;unauthorized.mockClear();configureRequests(() => ({ token: 'TEST-ONLY-token', factoryId: 'A', revision }), unauthorized) })
describe('Base request contract', () => {
  it('sends identity and selected factory, with no response fallback', async() => { const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ items: [], total: 0, offset: 0, limit: 20 }), { headers: { 'Content-Type': 'application/json' }}));vi.stubGlobal('fetch', fetcher);const result = await request('/api/demo', { query: { offset: 0, limit: 20 }});expect(result).toEqual({ items: [], total: 0, offset: 0, limit: 20 });const [url, options] = fetcher.mock.calls[0]!;expect(url).toBe('/api/demo?offset=0&limit=20');expect(options.headers.get('X-Factory-Id')).toBe('A');expect(options.headers.get('Authorization')).toBe('Bearer TEST-ONLY-token') })
  it('platform calls omit Factory context', async() => { const fetcher = vi.fn().mockResolvedValue(new Response('{}'));vi.stubGlobal('fetch', fetcher);await request('/api/system/user/list', { scope: 'platform' });expect(fetcher.mock.calls[0]![1].headers.has('X-Factory-Id')).toBe(false) })
  it('public login omits credentials from old identity', async() => { const fetcher = vi.fn().mockResolvedValue(new Response('{}'));vi.stubGlobal('fetch', fetcher);await request('/api/platform/session', { public: true, scope: 'platform', method: 'POST', body: { username: 'TEST', password: 'TEST ONLY' }});expect(fetcher.mock.calls[0]![1].headers.has('Authorization')).toBe(false) })
  it('401 clears identity and retains safe request correlation', async() => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify({ errorCode: 'UNAUTHENTICATED', message: 'Authentication required', requestId: 'TEST-ID' }), { status: 401 })));try { await request('/api/demo');throw new Error('expected error') } catch(e) { expect(e).toBeInstanceOf(ApiError);expect((e as ApiError).requestId).toBe('TEST-ID');expect((e as Error).message).toContain('重新登录') }expect(unauthorized).toHaveBeenCalledOnce() })
  it('403 remains a failure even when body resembles legacy AjaxResult', async() => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('{"code":200}', { status: 403 })));await expect(request('/api/demo')).rejects.toMatchObject({ status: 403 }) })
  it('rejects stale data after factory change', async() => { vi.stubGlobal('fetch', vi.fn().mockImplementation(async() => { revision++;return new Response('{}') }));await expect(request('/api/demo')).rejects.toMatchObject({ code: 'CONTEXT_CHANGED' }) })
  it('represents network failure explicitly', async() => { vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('TEST ONLY internal detail')));await expect(request('/api/demo')).rejects.toMatchObject({ code: 'NETWORK_ERROR' });await expect(request('/api/demo')).rejects.not.toThrow('internal detail') })
  it('multipart upload leaves content-type boundary to browser', async() => { const fetcher = vi.fn().mockResolvedValue(new Response('{}'));vi.stubGlobal('fetch', fetcher);await request('/api/platform/files', { method: 'POST', body: new FormData() });expect(fetcher.mock.calls[0]![1].headers.has('Content-Type')).toBe(false) })
})
