<script setup lang="ts">
import { saveAs } from 'file-saver'
import { ref, computed, watch, onUnmounted } from 'vue';import { request, requestBlob } from '@/lib/request';import { useAuth } from '@/stores/auth';import { ElMessage } from 'element-plus'
/** Source FileUpload/ImageUpload PORT. Persist private IDs, retrieve previews with authentication. */
const props = withDefaults(defineProps<{ limit?: number;fileSize?: number;fileType?: string[];isShowTip?: boolean;resource?: string;images?: boolean }>(), { limit: 5, fileSize: 10, fileType: () => [], isShowTip: true, resource: 'personal', images: false })
const model = defineModel<string>({ default: '' }), busy = ref(false), auth = useAuth(), ids = computed(() => model.value ? model.value.split(',').filter(Boolean) : [])
interface FileView { id: string;name: string;url?: string;error?: string }
const files = ref<FileView[]>([]), selection = ref<FileView[]>([]), picker = ref(false), picked = ref<string[]>([]);let version = 0
function release() { for (const f of files.value) if (f.url)URL.revokeObjectURL(f.url);files.value = [] }
watch(() => [model.value, props.resource, auth.revision], async() => { const current = ++version;release();if (!auth.loggedIn) return;const rows = await Promise.all(ids.value.map(async(id):Promise<FileView> => { try { const m = await request<{ orignalName: string }>('/api/platform/files/' + id, { query: { resource: props.resource }});const row:FileView = { id, name: m.orignalName };if (props.images) { const blob = await requestBlob('/api/platform/files/' + id + '/content', { query: { resource: props.resource }});if (current !== version) return row;row.url = URL.createObjectURL(blob) } return row } catch { return { id, name: '附件不可用', error: '资源不在当前范围或已删除' } } }));if (current === version)files.value = rows;else for (const row of rows) if (row.url)URL.revokeObjectURL(row.url) }, { immediate: true })
onUnmounted(() => { version++;release() })
async function upload({ file, onSuccess, onError }:any) { try { if (ids.value.length >= props.limit || file.size > props.fileSize * 1024 * 1024) throw new Error('文件数量或大小超出限制');if (props.fileType?.length && !props.fileType.includes(file.name.split('.').pop()?.toLowerCase())) throw new Error('文件类型不符合要求');busy.value = true;const form = new FormData();form.set('file', file);const value = await request<{ fileId: string }>('/api/platform/files', { method: 'POST', query: { resource: props.resource }, body: form });model.value = [...ids.value, value.fileId].join(',');onSuccess(value) } catch(e) { ElMessage.error(e instanceof Error ? e.message : '上传失败');onError(e) } finally { busy.value = false } }
async function download(id:string) { try { const meta = await request<{ orignalName: string }>('/api/platform/files/' + id, { query: { resource: props.resource }});const blob = await requestBlob('/api/platform/files/' + id + '/content', { query: { resource: props.resource }});saveAs(blob, meta.orignalName) } catch(e) { ElMessage.error(e instanceof Error ? e.message : '下载失败') } }
function unlink(id:string) { model.value = ids.value.filter(f => f !== id).join(',') }
async function choose() { try { const result = await request<{ rows: { fileId: string;orignalName: string }[] }>('/api/platform/files', { query: { resource: props.resource, offset: 0, limit: 100 }});selection.value = result.rows.filter(f => !ids.value.includes(f.fileId) && (!props.images || /\.(png|jpe?g|gif|webp)$/i.test(f.orignalName))).map(f => ({ id: f.fileId, name: f.orignalName }));picked.value = [];picker.value = true } catch(e) { ElMessage.error(e instanceof Error ? e.message : '读取文件失败') } }
function confirmPick() { if (ids.value.length + picked.value.length > props.limit) { ElMessage.warning('文件数量超出限制');return }model.value = [...ids.value, ...picked.value].join(',');picker.value = false }
</script><template><div class="source-file-upload"><div class="upload-actions"><el-upload action="#" :http-request="upload" :show-file-list="false" :accept="fileType?.map(t=>'.'+t).join(',')" :disabled="busy||ids.length>=limit"><el-button type="primary" :loading="busy">{{ images?'上传图片':'上传文件' }}</el-button></el-upload><el-button :disabled="busy||ids.length>=limit" @click="choose">选择已有文件</el-button></div><p v-if="isShowTip" class="muted">最多 {{ limit }} 个{{ images?'图片':'文件' }}，每个不超过 {{ fileSize }} MB<span v-if="fileType?.length">；类型：{{ fileType.join(' / ') }}</span></p><ul :class="{thumbnails:images}"><li v-for="file in files" :key="file.id"><el-image v-if="images&&file.url" :src="file.url" :preview-src-list="files.filter(f=>f.url).map(f=>f.url!)" fit="cover" preview-teleported /><span v-if="file.error" class="muted">{{ file.error }}</span><el-button v-else link @click="download(file.id)">{{ file.name }}</el-button><el-button link type="danger" @click="unlink(file.id)">移除选择</el-button></li></ul><el-dialog v-model="picker" title="选择当前范围内的私有文件" width="600px" append-to-body><el-checkbox-group v-model="picked"><div v-for="file in selection" :key="file.id"><el-checkbox :value="file.id">{{ file.name }}</el-checkbox></div></el-checkbox-group><el-empty v-if="!selection.length" description="暂无可选文件" /><template #footer><el-button @click="picker=false">取消</el-button><el-button type="primary" @click="confirmPick">确定</el-button></template></el-dialog></div></template><style scoped>.upload-actions{display:flex;gap:12px}.source-file-upload ul{padding:0;list-style:none}.source-file-upload li{padding:8px;display:flex;gap:8px;align-items:center}.thumbnails{display:flex;flex-wrap:wrap;gap:12px}.source-file-upload .thumbnails li{flex-direction:column;width:144px;border:1px solid #dcdfe6;border-radius:6px}.thumbnails .el-image{width:120px;height:100px}</style>
