<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue';import {request} from '@/lib/request';import {ElMessage} from 'element-plus';import DOMPurify from 'dompurify';import {useRouter} from 'vue-router';import {useAuth} from '@/stores/auth'
interface Message {messageId:string;messageTitle:string;messageContent:string;senderNick:string;messageLevel:string;status:string;callBack:string;createTime:string}
const rows=ref<Message[]>([]),loading=ref(false),total=ref(0),page=ref(1),selected=ref<Message>(),open=ref(false),router=useRouter(),auth=useAuth();let refreshTimer:ReturnType<typeof setInterval>|undefined;let stream:AbortController|undefined
async function load(){loading.value=true;try{const data=await request<{rows:Message[];total:number}>('/api/system/inbox',{scope:'platform',query:{pageNum:page.value,pageSize:20}});rows.value=data.rows;total.value=data.total}finally{loading.value=false}}
async function read(row:Message){selected.value=row;open.value=true;if(row.status!=='READ'){await request('/api/system/inbox/'+row.messageId+'/read',{method:'PUT',scope:'platform'});await load()}}
function follow(){const path=selected.value?.callBack;if(path&&/^\/(?!\/)[A-Za-z0-9/_?=&.-]{0,250}$/.test(path)){open.value=false;router.push(path)}}
async function subscribe(){stream=new AbortController();try{const response=await fetch('/api/system/inbox/events',{headers:{Authorization:'Bearer '+auth.token},signal:stream.signal});if(!response.ok||!response.body)return;const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(!stream.signal.aborted){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let split;while((split=buffer.indexOf('\n\n'))>=0){const event=buffer.slice(0,split);buffer=buffer.slice(split+2);if(event.includes('event:inbox-changed'))await load()}}}catch{/* Normal connection end/expiry; periodic authenticated refresh remains available. */}}
onMounted(()=>{load();subscribe();refreshTimer=setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{})},30000)});onUnmounted(()=>{stream?.abort();if(refreshTimer)clearInterval(refreshTimer)})
</script><template><section class="page"><h1>我的消息</h1><el-button @click="load">刷新</el-button><el-table :data="rows" v-loading="loading" empty-text="暂无消息"><el-table-column prop="messageTitle" label="标题" min-width="200"/><el-table-column prop="senderNick" label="发送人"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.status==='READ'?'info':'primary'">{{row.status==='READ'?'已读':'未读'}}</el-tag></template></el-table-column><el-table-column prop="createTime" label="发送时间" width="180"/><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="read(row)">查看</el-button></template></el-table-column></el-table><el-pagination v-if="total" v-model:current-page="page" :total="total" :page-size="20" @current-change="load" layout="total,prev,pager,next"/><el-dialog v-model="open" :title="selected?.messageTitle" width="600px"><div v-html="DOMPurify.sanitize(selected?.messageContent??'',{FORBID_TAGS:['img','iframe','video']})"/><template #footer><el-button @click="open=false">关闭</el-button><el-button v-if="selected?.callBack" type="primary" @click="follow">处理消息</el-button></template></el-dialog></section></template>
