<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import CrudPage from '@/components/CrudPage.vue'
import { pages, pageApi } from '@/lib/platform'
import { request } from '@/lib/request'
import { useAuth } from '@/stores/auth'
import type { Row, Page } from '@/lib/crud'
const route = useRoute(), auth = useAuth();const page = computed(() => pages[String(route.params.resource)]), api = computed(() => page.value ? pageApi(page.value) : null)
const links = ref<string[]>([]), options = ref<Row[]>([]), dialog = ref(false), saving = ref(false), linkPath = ref(''), linkTitle = ref('')
async function assign(row:Row) { try { const users = page.value?.resource === 'users';linkPath.value = '/api/platform/' + (users ? 'users' : 'roles') + '/' + row.id + '/' + (users ? 'roles' : 'menus');linkTitle.value = users ? '分配角色' : '分配菜单与按钮';links.value = (await request<{ ids: string[] }>(linkPath.value, { scope: 'platform' })).ids;options.value = (await request<Page>('/api/platform/' + (users ? 'roles' : 'menus'), { scope: 'platform', query: { offset: 0, limit: 100 }})).items;dialog.value = true } catch(e) { ElMessage.error(e instanceof Error ? e.message : '加载失败') } }
async function saveLinks() { saving.value = true;try { await request(linkPath.value, { method: 'PUT', body: { ids: links.value }, scope: 'platform' });await auth.loadNavigation();dialog.value = false;ElMessage.success('已更新授权') } catch(e) { ElMessage.error(e instanceof Error ? e.message : '授权失败') } finally { saving.value = false } }
async function password(row:Row) { try { const result = await ElMessageBox.prompt('新密码至少12位，保存后撤销该账号所有会话。', '重置密码', { inputType: 'password', inputPattern: /^.{12,128}$/, inputErrorMessage: '请输入12–128位密码', confirmButtonText: '保存', cancelButtonText: '取消' });await request('/api/platform/users/' + row.id + '/password', { method: 'PUT', body: { password: result.value }, scope: 'platform' });ElMessage.success('密码已重置') } catch(e) { if (e === 'cancel' || e === 'close') return;ElMessage.error(e instanceof Error ? e.message : '重置失败') } }
async function run(row:Row) { try { await ElMessageBox.confirm('按任务登记的范围立即执行一次。', '执行任务', { confirmButtonText: '立即执行', cancelButtonText: '取消' });await request('/api/platform/jobs/' + row.id + '/run', { method: 'POST', scope: 'platform' });ElMessage.success('任务执行完成') } catch(e) { if (e === 'cancel' || e === 'close') return;ElMessage.error(e instanceof Error ? e.message : '执行失败') } }
</script>
<template><CrudPage v-if="page&&api" :key="page.resource" :title="page.title" :api="api" :permission="page.permission" permission-scope="platform" :fields="page.fields" :readonly="page.readonly" :searchable="false"><template #actions="{row}"><el-button v-if="['users','roles'].includes(page.resource)&&auth.hasPermission(page.permission+':write','platform')" text type="primary" @click="assign(row)">授权</el-button><el-button v-if="page.resource==='users'&&auth.hasPermission('platform:users:write','platform')" text @click="password(row)">密码</el-button><el-button v-if="page.resource==='jobs'&&auth.hasPermission('platform:jobs:run','platform')" text type="primary" @click="run(row)">立即执行</el-button></template></CrudPage><el-empty v-else description="页面未登记" /><el-dialog v-model="dialog" :title="linkTitle" width="min(560px,92vw)"><p class="muted">权限逐请求生效。工厂角色仅作用于其所属工厂。</p><el-select v-model="links" multiple filterable style="width:100%"><el-option v-for="option in options" :key="String(option.id)" :label="String(option.name)" :value="String(option.id)" /></el-select><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveLinks">保存授权</el-button></template></el-dialog></template>
