<script setup lang="ts">
import {ref,onMounted} from 'vue';import request from '@/utils/request'
interface Pool {name:string;activeCount:number;poolingCount:number;connectCount:number;closeCount:number;createCount:number;destroyCount:number;errorCount:number;waitCount:number;queryCount:number}
interface Sql {id:string;sql:string;executeCount:string;errorCount:string;totalMillis:string;maxMillis:string;updateCount:string;fetchRowCount:string}
interface Wall {enabled:boolean;checkCount:string;violationCount:string;whiteListHitCount:string;blackListHitCount:string}
const stats=ref<Pool>(),queries=ref<Sql[]>([]),wall=ref<Wall>(),error=ref(''),loading=ref(false),active=ref('pool')
const labels:Record<keyof Pool,string>={name:'数据源名称',activeCount:'活跃连接',poolingCount:'空闲连接',connectCount:'借用连接次数',closeCount:'归还连接次数',createCount:'创建连接次数',destroyCount:'销毁连接次数',errorCount:'连接错误次数',waitCount:'等待连接次数',queryCount:'SQL 执行次数'}
async function refresh(){loading.value=true;try{const [pool,sql,firewall]=await Promise.all([request({url:'/monitor/druid'}),request({url:'/monitor/druid/sql'}),request({url:'/monitor/druid/wall'})]);stats.value=pool.data;queries.value=sql.data;wall.value=firewall.data;error.value=''}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}onMounted(refresh)
</script><template><div class="app-container" v-loading="loading">
    <PageHeader title="数据源监控" description="连接池、SQL 统计与防火墙" /><div class="monitor-heading"><span class="muted small">实时数据源信息</span><el-button @click="refresh" :loading="loading">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-tabs v-model="active"><el-tab-pane label="数据源" name="pool"><el-descriptions v-if="stats" :column="2" border><el-descriptions-item v-for="(value,key) in stats" :key="key" :label="labels[key]">{{value}}</el-descriptions-item></el-descriptions></el-tab-pane><el-tab-pane label="SQL 统计" name="sql"><el-table :data="queries" empty-text="暂无已执行 SQL"><el-table-column prop="sql" label="SQL 模板" min-width="420" show-overflow-tooltip/><el-table-column prop="executeCount" label="执行次数" width="100"/><el-table-column prop="errorCount" label="错误次数" width="100"/><el-table-column prop="totalMillis" label="总耗时(ms)" width="120"/><el-table-column prop="maxMillis" label="最大耗时(ms)" width="130"/><el-table-column prop="updateCount" label="更新行数" width="100"/><el-table-column prop="fetchRowCount" label="读取行数" width="100"/></el-table></el-tab-pane><el-tab-pane label="SQL 防火墙" name="wall"><el-descriptions v-if="wall?.enabled" :column="2" border><el-descriptions-item label="检查次数">{{wall.checkCount}}</el-descriptions-item><el-descriptions-item label="违规次数">{{wall.violationCount}}</el-descriptions-item><el-descriptions-item label="白名单命中">{{wall.whiteListHitCount}}</el-descriptions-item><el-descriptions-item label="黑名单命中">{{wall.blackListHitCount}}</el-descriptions-item></el-descriptions><el-alert v-else-if="wall" type="info" title="当前数据源未启用 SQL 防火墙" :closable="false"/></el-tab-pane></el-tabs></div></template><style scoped>.monitor-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}</style>
