<script setup lang="ts">
import { computed, ref, watch } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage } from 'element-plus'
import { useAuth } from '@/stores/auth';import SidebarNode from '@/components/SidebarNode.vue'
const auth=useAuth(),route=useRoute(),router=useRouter(),mobile=ref(false),tags=ref<{path:string;name:string}[]>([])
watch(()=>route.fullPath,()=>{if(route.path!=='/login'&&!tags.value.some(t=>t.path===route.path)){if(tags.value.length>=10)tags.value.shift();tags.value.push({path:route.path,name:String(route.meta.title??'工作页面')})}mobile.value=false})
watch(()=>auth.loggedIn,logged=>{if(!logged){tags.value=[];router.replace('/login')}})
async function select(value:string){try{await auth.selectFactory(value);await router.replace('/')}catch(e){ElMessage.error(e instanceof Error?e.message:'工厂切换失败')}}
async function logout(){try{await auth.logout()}catch(e){ElMessage.error(e instanceof Error?e.message:'服务端注销未确认')}finally{router.replace('/login')}}
</script><template><RouterView v-if="route.path==='/login'"/><div v-else class="app-shell"><aside :class="{open:mobile}"><RouterLink to="/" class="brand">MES <span>Base</span></RouterLink><div class="nav-node"><RouterLink to="/files">个人文件</RouterLink></div><p class="nav-label">PLATFORM</p><SidebarNode v-for="menu in auth.platformMenus" :key="menu.id" :menu="menu"/><p v-if="auth.factoryId" class="nav-label">FACTORY · {{auth.factoryId}}</p><SidebarNode v-for="menu in auth.factoryMenus" :key="menu.id" :menu="menu"/><p v-if="!auth.platformMenus.length&&!auth.factoryMenus.length" class="nav-empty">当前范围暂无授权菜单</p></aside><div class="workspace"><header class="navbar"><el-button text class="mobile-menu" @click="mobile=!mobile">菜单</el-button><span class="muted">管理工作台</span><div class="navbar-actions"><el-select :model-value="auth.factoryId" clearable placeholder="选择工厂（可选）" @change="select"><el-option v-for="f in auth.factories" :key="f.factoryId" :label="f.name" :value="f.factoryId"/></el-select><span>{{auth.username}}</span><el-button text @click="logout">退出登录</el-button></div></header><nav class="tags"><RouterLink to="/">概览</RouterLink><RouterLink v-for="tag in tags.filter(t=>t.path!=='/')" :key="tag.path" :to="tag.path">{{tag.name}}</RouterLink></nav><main><RouterView/></main></div></div></template>
